fix: fix compiler nodeResolve
carlos-menezes/altv-typescript-react-starter pull request #4
Opened 2024-03-23 08:30 UTC by SarotaM

2024-03-23 12:01 UTC, carlos-menezes requested changes
Thank you for submitting the PR!

2024-03-23 12:01 UTC, carlos-menezes commented on scripts/compiler.ts
> +                nodeResolve({ extensions: ['.js', '.jsx', '.ts', '.tsx'] }),
We only want to resolve `ts` files.

2024-03-23 21:32 UTC, SarotaM commented on scripts/compiler.ts
> +                nodeResolve({ extensions: ['.js', '.jsx', '.ts', '.tsx'] }),
I'll fix it on Monday 😊

2024-03-26 22:21 UTC, carlos-menezes approved these changes

2024-03-26 22:21 UTC, merged